version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: pipenv
        displayName: pipenv安装与启用
        pythonVersion: '3.9'
        commands:
          - pwd
          - cd ./example
          - pip install pipenv
          - ln -s $(find / -name pipenv) /usr/bin/pipenv
          - pipenv install
          - pipenv shell
        artifacts:
          - name: pipenvTemp
            path:
              - ./
        strategy:
          retry: '3'
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: test
        displayName: 测试执行
        pythonVersion: '3.9'
        commands:
          - py ./initsql.py
          - py ./app.py
        artifacts:
          - name: runTemp
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '3'
